// This file is generated by the FlutterFire CLI.
// DO NOT commit this file with real credentials to source control.
// Add lib/firebase_options.dart to .gitignore after generation.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web: go to Firebase Console → Project Settings → Your apps → Add app → Web
  // Then replace the values below with the config snippet Firebase provides.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHUW-DvOSCi2CsBshamPMup4fKMxHxO2g',
    appId: '1:861507979595:web:26c6c7f2fa98f03d55c0ce',
    messagingSenderId: '861507979595',
    projectId: 'clinika-flow',
    authDomain: 'clinika-flow.firebaseapp.com',
    storageBucket: 'clinika-flow.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3pNwnY1h8FgjWcgtXhKoRlRwM4B2o7NQ',
    appId: '1:861507979595:android:c797fa6f23b57da655c0ce',
    messagingSenderId: '861507979595',
    projectId: 'clinika-flow',
    storageBucket: 'clinika-flow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjeTrYU8e96HlySh8U_ok2xWSdk8PA9so',
    appId: '1:861507979595:ios:207294c0591706ad55c0ce',
    messagingSenderId: '861507979595',
    projectId: 'clinika-flow',
    storageBucket: 'clinika-flow.firebasestorage.app',
    iosClientId: null,
    iosBundleId: 'com.example.clinikaFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjeTrYU8e96HlySh8U_ok2xWSdk8PA9so',
    appId: '1:861507979595:ios:207294c0591706ad55c0ce',
    messagingSenderId: '861507979595',
    projectId: 'clinika-flow',
    storageBucket: 'clinika-flow.firebasestorage.app',
    iosClientId: null,
    iosBundleId: 'com.example.clinikaFlow',
  );
}
